// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1_delete.Models;

namespace WebApplication1_delete.Migrations.Record
{
    [DbContext(typeof(RecordContext))]
    [Migration("20190708204137_changedDataType2")]
    partial class changedDataType2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1_delete.Models.Record", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Album")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("Image");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecordID");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
