//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public string Band { get; set; }
        public string Album { get; set; }
        public Nullable<int> Year { get; set; }
        public string Genre { get; set; }
        public string Image { get; set; }
    }
}
